spring.application.name=galeria-seleta-api
server.port=8080

logging.level.com.galeriaseleta=DEBUG

# SQLite
spring.datasource.url=jdbc:sqlite:./galeria_seleta.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Inicializa o schema.sql na startup (CREATE TABLE IF NOT EXISTS e seguro rodar sempre)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JWT (futuro)
# jwt.secret=sua-chave-secreta
# jwt.expiration=86400000
