// Este arquivo configura o Maven Wrapper — ele permite rodar o projeto sem ter o Maven instalado globalmente.
// URL de onde baixar o Maven automaticamente na primeira execução
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
// o Bin no fin da linha bin = baixa só os binários (sem código-fonte)

// Versão do script wrapper (não do Maven em si)
wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.2/maven-wrapper-3.3.2.jar
